service: serverless-graphql-typescript

frameworkVersion: '>=1.21.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    AWS_ACCESS_KEY_ID: AKIAIOLMTMR3KTDDC52Q
    AWS_SECRET_ACCESS_KEY: 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
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:us-east-1:*:table/*'

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

custom:
  serverless-offline:
    port: 4000
  webpackIncludeModules: true
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  uploadFile:
    handler: src/handler.uploadFile
    events:
      - http:
          path: uploadFile
          method: post
          cors: true
  getFile:
    handler: src/handler.getFile
    events:
      - http:
          path: getFile
          method: get
          cors: true
  getImage:
    handler: src/handler.getImage
    events:
      - http:
          path: getImage
          method: get
          cors: true
